// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20250601141625_AgregarRolesSerializadosAUsuario")]
    partial class AgregarRolesSerializadosAUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Dominio.Proyecto", b =>
                {
                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaInicioEstimada")
                        .HasColumnType("datetime2");

                    b.Property<string>("_nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Nombre");

                    b.ToTable("Proyecto");
                });

            modelBuilder.Entity("Backend.Dominio.Recurso", b =>
                {
                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TareaEF_Titulo")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Nombre");

                    b.HasIndex("TareaEF_Titulo");

                    b.ToTable("Recurso");
                });

            modelBuilder.Entity("Backend.Dominio.Tarea", b =>
                {
                    b.Property<string>("EF_Titulo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Titulo");

                    b.Property<int>("DuracionEnDias")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaEjecucion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProyectoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Realizada")
                        .HasColumnType("bit");

                    b.Property<string>("_titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EF_Titulo");

                    b.HasIndex("ProyectoNombre");

                    b.ToTable("Tarea");
                });

            modelBuilder.Entity("Backend.Dominio.Usuario", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RolesSerializados")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Email = "adminSistema@mail.com",
                            Apellido = "Sistema",
                            FechaNacimiento = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Admin",
                            Password = "Pass123@",
                            RolesSerializados = "AdminSistema"
                        },
                        new
                        {
                            Email = "adminProyecto@mail.com",
                            Apellido = "Proyecto",
                            FechaNacimiento = new DateTime(1998, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Admin",
                            Password = "Pass123@",
                            RolesSerializados = "AdminProyecto"
                        },
                        new
                        {
                            Email = "miembro@mail.com",
                            Apellido = "Proyecto",
                            FechaNacimiento = new DateTime(1988, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Miembro",
                            Password = "Pass123@",
                            RolesSerializados = "MiembroProyecto"
                        });
                });

            modelBuilder.Entity("ProyectoUsuario", b =>
                {
                    b.Property<string>("ListaProyectosNombre")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ListaUsuariosEmail")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ListaProyectosNombre", "ListaUsuariosEmail");

                    b.HasIndex("ListaUsuariosEmail");

                    b.ToTable("ProyectoUsuario");
                });

            modelBuilder.Entity("TareaTarea", b =>
                {
                    b.Property<string>("DependenciasEF_Titulo")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RequeridoresEF_Titulo")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DependenciasEF_Titulo", "RequeridoresEF_Titulo");

                    b.HasIndex("RequeridoresEF_Titulo");

                    b.ToTable("TareaTarea");
                });

            modelBuilder.Entity("Backend.Dominio.Recurso", b =>
                {
                    b.HasOne("Backend.Dominio.Tarea", null)
                        .WithMany("Recursos")
                        .HasForeignKey("TareaEF_Titulo");
                });

            modelBuilder.Entity("Backend.Dominio.Tarea", b =>
                {
                    b.HasOne("Backend.Dominio.Proyecto", "Proyecto")
                        .WithMany("ListaDeTareas")
                        .HasForeignKey("ProyectoNombre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("ProyectoUsuario", b =>
                {
                    b.HasOne("Backend.Dominio.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ListaProyectosNombre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Dominio.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ListaUsuariosEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TareaTarea", b =>
                {
                    b.HasOne("Backend.Dominio.Tarea", null)
                        .WithMany()
                        .HasForeignKey("DependenciasEF_Titulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Dominio.Tarea", null)
                        .WithMany()
                        .HasForeignKey("RequeridoresEF_Titulo")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Dominio.Proyecto", b =>
                {
                    b.Navigation("ListaDeTareas");
                });

            modelBuilder.Entity("Backend.Dominio.Tarea", b =>
                {
                    b.Navigation("Recursos");
                });
#pragma warning restore 612, 618
        }
    }
}
