// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(SqlContext))]
    partial class SqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Dominio.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UsuarioEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Vista")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioEmail");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Backend.Dominio.Proyecto", b =>
                {
                    b.Property<string>("Nombre")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("FechaInicioEstimada")
                        .HasColumnType("datetime2");

                    b.Property<string>("LiderEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Nombre");

                    b.HasIndex("LiderEmail");

                    b.ToTable("Proyecto", (string)null);
                });

            modelBuilder.Entity("Backend.Dominio.RangoFecha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Desde")
                        .HasColumnType("datetime2")
                        .HasColumnName("Desde");

                    b.Property<DateTime>("Hasta")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecursoId")
                        .HasColumnType("int");

                    b.Property<string>("TareaTitulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("RecursoId");

                    b.HasIndex("TareaTitulo");

                    b.ToTable("RangosFecha");
                });

            modelBuilder.Entity("Backend.Dominio.Recurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Funcionalidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProyectoNombre")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Usos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UtilizadoHasta")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoNombre");

                    b.ToTable("Recurso", (string)null);
                });

            modelBuilder.Entity("Backend.Dominio.Tarea", b =>
                {
                    b.Property<string>("Titulo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Titulo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuracionEnDias")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaEjecucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicioForzada")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaInicioForzada");

                    b.Property<string>("ProyectoNombre")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Realizada")
                        .HasColumnType("bit");

                    b.HasKey("Titulo");

                    b.HasIndex("ProyectoNombre");

                    b.ToTable("Tarea", (string)null);
                });

            modelBuilder.Entity("Backend.Dominio.Usuario", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RolesSerializados")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Email = "adminSistema@mail.com",
                            Apellido = "Sistema",
                            FechaNacimiento = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Admin",
                            Password = "da05b1c555994f4d34f0b5e14fd340c7fdb0a263a8cf41625cc2200ea43c3b92",
                            RolesSerializados = "AdminSistema"
                        });
                });

            modelBuilder.Entity("ProyectoUsuario", b =>
                {
                    b.Property<string>("ListaProyectosNombre")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ListaUsuariosEmail")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ListaProyectosNombre", "ListaUsuariosEmail");

                    b.HasIndex("ListaUsuariosEmail");

                    b.ToTable("ProyectoUsuario");
                });

            modelBuilder.Entity("RecursoTarea", b =>
                {
                    b.Property<int>("RecursosId")
                        .HasColumnType("int");

                    b.Property<string>("TareasTitulo")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("RecursosId", "TareasTitulo");

                    b.HasIndex("TareasTitulo");

                    b.ToTable("TareaRecurso", (string)null);
                });

            modelBuilder.Entity("TareaDependencia", b =>
                {
                    b.Property<string>("DependenciaId")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TareaId")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DependenciaId", "TareaId");

                    b.HasIndex("TareaId");

                    b.ToTable("TareaDependencia");
                });

            modelBuilder.Entity("Backend.Dominio.Notificacion", b =>
                {
                    b.HasOne("Backend.Dominio.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Backend.Dominio.Proyecto", b =>
                {
                    b.HasOne("Backend.Dominio.Usuario", "Lider")
                        .WithMany()
                        .HasForeignKey("LiderEmail")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lider");
                });

            modelBuilder.Entity("Backend.Dominio.RangoFecha", b =>
                {
                    b.HasOne("Backend.Dominio.Recurso", "Recurso")
                        .WithMany("FechasDeUso")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Dominio.Tarea", "Tarea")
                        .WithMany("RangosDeUso")
                        .HasForeignKey("TareaTitulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recurso");

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("Backend.Dominio.Recurso", b =>
                {
                    b.HasOne("Backend.Dominio.Proyecto", "Proyecto")
                        .WithMany("Recursos")
                        .HasForeignKey("ProyectoNombre");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("Backend.Dominio.Tarea", b =>
                {
                    b.HasOne("Backend.Dominio.Proyecto", "Proyecto")
                        .WithMany("ListaDeTareas")
                        .HasForeignKey("ProyectoNombre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("ProyectoUsuario", b =>
                {
                    b.HasOne("Backend.Dominio.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ListaProyectosNombre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Dominio.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ListaUsuariosEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecursoTarea", b =>
                {
                    b.HasOne("Backend.Dominio.Recurso", null)
                        .WithMany()
                        .HasForeignKey("RecursosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Dominio.Tarea", null)
                        .WithMany()
                        .HasForeignKey("TareasTitulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TareaDependencia", b =>
                {
                    b.HasOne("Backend.Dominio.Tarea", null)
                        .WithMany()
                        .HasForeignKey("DependenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Dominio.Tarea", null)
                        .WithMany()
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Dominio.Proyecto", b =>
                {
                    b.Navigation("ListaDeTareas");

                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("Backend.Dominio.Recurso", b =>
                {
                    b.Navigation("FechasDeUso");
                });

            modelBuilder.Entity("Backend.Dominio.Tarea", b =>
                {
                    b.Navigation("RangosDeUso");
                });

            modelBuilder.Entity("Backend.Dominio.Usuario", b =>
                {
                    b.Navigation("Notificaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
